import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getProduct } from '@/features/catalog/infrastructure/api';
import { AddToCartButton } from '@/features/cart/ui/add-to-cart-button';
import { formatMoney } from '@/shared/lib/format';
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const product = await getProduct(slug).catch(() => null); return { title: product?.name ?? 'Producto', description: product?.description }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const product = await getProduct(slug).catch(() => null); if (!product) notFound(); const image = product.images[0]; return <section className="page-container product-detail"><Link href="/catalog" className="back-link">← Volver al catálogo</Link><div className="detail-grid"><div className="detail-gallery"><div className="detail-main-image">{image ? <Image src={image.url} alt={image.altText || product.name} fill priority sizes="(max-width: 900px) 100vw, 55vw" /> : <div className="image-placeholder large"><span>◈</span></div>}</div></div><div className="detail-copy"><p className="eyebrow">{product.kind === 'SINGLE_CARD' ? 'Carta individual' : 'Producto sellado'} · {product.sku}</p><h1>{product.name}</h1><p className="detail-price">{formatMoney(product.price)}</p><p className="detail-description">{product.description}</p>{product.pokemonCard && <dl className="specs"><div><dt>Set</dt><dd>{product.pokemonCard.setName}</dd></div><div><dt>Número</dt><dd>{product.pokemonCard.cardNumber}</dd></div><div><dt>Rareza</dt><dd>{product.pokemonCard.rarity}</dd></div><div><dt>Condición</dt><dd>{product.pokemonCard.condition}</dd></div><div><dt>Idioma</dt><dd>{product.pokemonCard.language}</dd></div>{product.pokemonCard.finish && <div><dt>Acabado</dt><dd>{product.pokemonCard.finish}</dd></div>}</dl>}<div className="detail-cta"><AddToCartButton product={product} /><p>{product.available > 0 ? `${product.available} disponibles · stock verificado al comprar` : 'Actualmente sin stock'}</p></div></div></div></section>; }
