'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useQuery } from '@tanstack/react-query';
import { Eye, Plus, Search } from 'lucide-react';
import { useState } from 'react';
import { AdminDataTable, AdminPageHeader, Button, CursorPagination, SelectField, TextField } from '@/components';
import { adminErrorMessage } from '@/shared/admin/client';
import { adminMoney, AdminBadge } from '@/shared/admin/format';
import { listAdminProducts } from '../infrastructure/api';

export function AdminProductListView() {
  const [filters, setFilters] = useState({ search: '', status: '', kind: '', stock: '', pokemonType: '', setName: '' });
  const [cursor, setCursor] = useState<string | undefined>();
  const [history, setHistory] = useState<Array<string | undefined>>([]);
  const query = useQuery({ queryKey: ['admin', 'products', filters, cursor], queryFn: () => listAdminProducts({ ...filters, cursor, limit: 25 }), placeholderData: (previous) => previous });
  const apply = (key: keyof typeof filters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setCursor(undefined); setHistory([]); };
  return <><AdminPageHeader eyebrow="Catálogo interno" title="Productos" description="Creá, publicá y mantené el inventario completo de la tienda." actions={<Link className="button button-primary" href="/admin/products/new"><Plus size={16} />Nuevo producto</Link>} />
    <div className="admin-toolbar"><TextField className="admin-search-field" label="Buscar" value={filters.search} onChange={(event) => apply('search', event.target.value)} placeholder="SKU, nombre o slug" /><SelectField label="Estado" value={filters.status} onChange={(event) => apply('status', event.target.value)}><option value="">Todos</option><option value="DRAFT">Borradores</option><option value="PUBLISHED">Publicados</option><option value="ARCHIVED">Archivados</option></SelectField><SelectField label="Clase" value={filters.kind} onChange={(event) => apply('kind', event.target.value)}><option value="">Todas</option><option value="SINGLE_CARD">Cartas individuales</option><option value="SEALED_PRODUCT">Sellados</option><option value="ACCESSORY">Accesorios</option></SelectField><SelectField label="Stock" value={filters.stock} onChange={(event) => apply('stock', event.target.value)}><option value="">Todo</option><option value="AVAILABLE">Disponible</option><option value="LOW">Bajo</option><option value="OUT">Sin stock</option></SelectField><SelectField label="Tipo Pokémon" value={filters.pokemonType} onChange={(event) => apply('pokemonType', event.target.value)}><option value="">Todos</option>{['COLORLESS','DARKNESS','DRAGON','FAIRY','FIGHTING','FIRE','GRASS','LIGHTNING','METAL','PSYCHIC','WATER'].map((value) => <option key={value} value={value}>{value}</option>)}</SelectField><TextField label="Colección / set" value={filters.setName} onChange={(event) => apply('setName', event.target.value)} /><Button variant="secondary" onClick={() => void query.refetch()} aria-label="Actualizar resultados"><Search size={16} />Buscar</Button></div>
    {query.isLoading ? <div className="admin-loading">Cargando productos</div> : query.isError ? <div className="admin-error-panel"><div><h2>No pudimos cargar los productos</h2><p>{adminErrorMessage(query.error)}</p><Button variant="secondary" onClick={() => void query.refetch()}>Reintentar</Button></div></div> : <><AdminDataTable caption="Productos administrativos" rows={query.data?.data ?? []} rowKey={(row) => row.id} columns={[{ key: 'product', header: 'Producto', render: (row) => <div className="admin-table-primary">{row.images[0] ? <Image src={row.images[0].url} alt="" width={46} height={56} unoptimized /> : <span className="admin-table-thumb" />}<div><Link className="admin-table-link" href={`/admin/products/${row.id}`}>{row.name}</Link><span>{row.sku} · {row.slug}</span></div></div> }, { key: 'kind', header: 'Clase', render: (row) => <AdminBadge value={row.kind} /> }, { key: 'status', header: 'Estado', render: (row) => <AdminBadge value={row.status} /> }, { key: 'stock', header: 'Disponible', align: 'center', render: (row) => <strong>{row.inventory.available}</strong> }, { key: 'price', header: 'Precio', align: 'right', render: (row) => <span className="admin-money">{adminMoney(row.price)}</span> }, { key: 'actions', header: 'Acción', align: 'right', render: (row) => <Link className="admin-icon-button" href={`/admin/products/${row.id}`} aria-label={`Abrir ${row.name}`}><Eye size={17} /></Link> }]} /><CursorPagination canPrevious={history.length > 0} canNext={Boolean(query.data?.nextCursor)} loading={query.isFetching} onPrevious={() => { const previous = [...history]; const value = previous.pop(); setHistory(previous); setCursor(value); }} onNext={() => { if (!query.data?.nextCursor) return; setHistory((current) => [...current, cursor]); setCursor(query.data.nextCursor ?? undefined); }} /></>}
  </>;
}
