'use client';

import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, Archive, Banknote, Boxes, ClipboardCheck, CreditCard, Mail, PackageCheck, RefreshCw, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import { AdminDataTable, AdminPageHeader, AdminStatCard, Button } from '@/components';
import { adminDate, adminMoney, AdminBadge } from '@/shared/admin/format';
import { adminErrorMessage } from '@/shared/admin/client';
import { getAdminDashboard } from '../infrastructure/api';
import type { DashboardRange } from '../domain/contracts';

const ranges: Array<{ value: DashboardRange; label: string }> = [{ value: 'TODAY', label: 'Hoy' }, { value: '7D', label: '7 días' }, { value: '30D', label: '30 días' }];

export function AdminDashboardView() {
  const [range, setRange] = useState<DashboardRange>('7D');
  const query = useQuery({ queryKey: ['admin', 'dashboard', range], queryFn: () => getAdminDashboard(range), refetchInterval: 30_000 });
  if (query.isLoading) return <div className="admin-loading">Cargando centro de operaciones</div>;
  if (query.isError || !query.data) return <div className="admin-error-panel"><div><h1>No pudimos cargar el dashboard</h1><p>{adminErrorMessage(query.error)}</p><Button variant="secondary" onClick={() => void query.refetch()}>Reintentar</Button></div></div>;
  const dashboard = query.data;
  return <>
    <AdminPageHeader eyebrow="Centro de operaciones" title="Dashboard" description="Trabajo pendiente, estado del catálogo y movimientos recientes." actions={<><div className="admin-range-picker">{ranges.map((item) => <button key={item.value} type="button" className={range === item.value ? 'is-active' : ''} onClick={() => setRange(item.value)}>{item.label}</button>)}</div><Button variant="secondary" onClick={() => void query.refetch()} disabled={query.isFetching}><RefreshCw size={16} />Actualizar</Button></>} />
    <section className="admin-stats" aria-label="Resumen"><AdminStatCard label="Cobrado bruto" value={adminMoney(dashboard.revenue.gross)} detail="Órdenes pagadas del período" icon={<TrendingUp size={16} />} tone="green" /><AdminStatCard label="Neto registrado" value={adminMoney(dashboard.revenue.net)} detail={`${adminMoney(dashboard.revenue.refunded)} reembolsado`} icon={<Banknote size={16} />} tone="cyan" /><AdminStatCard label="Órdenes" value={dashboard.orders.total} detail="Creadas en el período" icon={<ClipboardCheck size={16} />} tone="yellow" /><AdminStatCard label="Requieren atención" value={dashboard.attention.transferReviews + dashboard.attention.mercadoPagoReviews} detail="Pagos pendientes de revisión" icon={<AlertTriangle size={16} />} tone="purple" /></section>
    <div className="admin-grid"><section className="admin-panel admin-grid-main"><div className="admin-panel-header"><h2>Órdenes recientes</h2><Link href="/admin/orders">Ver todas →</Link></div><AdminDataTable caption="Órdenes recientes" rows={dashboard.recentOrders} rowKey={(row) => row.id} columns={[{ key: 'number', header: 'Orden', render: (row) => <Link className="admin-table-link" href={`/admin/orders/${row.number}`}>{row.number}</Link> }, { key: 'status', header: 'Estado', render: (row) => <AdminBadge value={row.status} /> }, { key: 'date', header: 'Fecha', render: (row) => adminDate(row.createdAt, true) }, { key: 'total', header: 'Total', align: 'right', render: (row) => <strong className="admin-money">{adminMoney(row.total)}</strong> }]} /></section>
      <aside className="admin-panel admin-grid-side"><div className="admin-panel-header"><h2>Colas operativas</h2></div><div className="admin-panel-body"><ul className="admin-list"><li><Link className="admin-list-row" href="/admin/payments?queue=TRANSFER_REVIEW"><div><strong>Transferencias</strong><span>Comprobantes para revisar</span></div><AdminBadge value={String(dashboard.attention.transferReviews)} /></Link></li><li><Link className="admin-list-row" href="/admin/payments?queue=MERCADO_PAGO_REVIEW"><div><strong>Mercado Pago</strong><span>Pagos con revisión manual</span></div><AdminBadge value={String(dashboard.attention.mercadoPagoReviews)} /></Link></li><li><Link className="admin-list-row" href="/admin/inventory?stock=OUT"><div><strong>Sin stock</strong><span>Productos no disponibles</span></div><AdminBadge value={String(dashboard.products.outOfStock)} /></Link></li><li><Link className="admin-list-row" href="/admin/inventory?stock=LOW"><div><strong>Stock bajo</strong><span>Disponibilidad de 1 a 5 unidades</span></div><AdminBadge value={String(dashboard.products.lowStock)} /></Link></li></ul><div className="admin-panel-subsection"><h3>Órdenes por estado</h3><ul className="admin-status-counts">{Object.entries(dashboard.orders.byStatus).map(([status, count]) => <li key={status}><AdminBadge value={status} /><strong>{count}</strong></li>)}</ul></div></div></aside>
    </div>
    <section className="admin-panel admin-activity-panel"><div className="admin-panel-header"><h2>Actividad administrativa reciente</h2><Link href="/admin/audit">Abrir auditoría →</Link></div><AdminDataTable caption="Actividad administrativa reciente" rows={dashboard.recentActivity} rowKey={(row) => row.id} empty="Todavía no hay acciones administrativas registradas." columns={[{ key: 'action', header: 'Acción', render: (row) => <AdminBadge value={row.action} /> }, { key: 'entity', header: 'Entidad', render: (row) => <div className="admin-table-primary"><div><strong>{row.entityType}</strong><span>{row.entityId ?? 'Sin referencia'}</span></div></div> }, { key: 'request', header: 'Request ID', render: (row) => row.requestId ?? '—' }, { key: 'date', header: 'Fecha', align: 'right', render: (row) => adminDate(row.createdAt, true) }]} /></section>
    <section className="admin-health-strip"><div><PackageCheck size={18} /><span>Publicados<strong>{dashboard.products.published}</strong></span></div><div><Boxes size={18} /><span>Borradores<strong>{dashboard.products.draft}</strong></span></div><div><Archive size={18} /><span>Archivados<strong>{dashboard.products.archived}</strong></span></div><div className={dashboard.integrations.bankTransfer ? 'is-ok' : 'is-off'}><Banknote size={18} /><span>Transferencia<strong>{dashboard.integrations.bankTransfer ? 'Configurada' : 'Inactiva'}</strong></span></div><div className={dashboard.integrations.mercadoPago ? 'is-ok' : 'is-off'}><CreditCard size={18} /><span>Mercado Pago<strong>{dashboard.integrations.mercadoPago ? 'Configurado' : 'Inactivo'}</strong></span></div><div className={dashboard.integrations.smtp ? 'is-ok' : 'is-off'}><Mail size={18} /><span>Correo SMTP<strong>{dashboard.integrations.smtp ? 'Configurado' : 'Inactivo'}</strong></span></div></section>
  </>;
}
